---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  default:
    desc: List tasks
    silent: true
    cmds:
      - task --list

  run:
    desc: Run solution
    silent: true
    requires:
      vars:
        - name: YEAR
          enum: ["2015", "2025"]
    cmds:
      - task -t "{{.YEAR}}" run YEAR="{{.YEAR}}" DAY="{{.DAY | default 1}}"
